GET http://localhost:7000/tickets

###

GET http://localhost:7000/animals

###

GET http://localhost:7000/animals/2

###

GET http://localhost:7000/animals?q=E

###

POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Toucans",
  "count": "19"
}

###

PATCH http://localhost:7000/animals/2
Content-Type: application/json

{
  "count": 245
}

###

DELETE http://localhost:7000/animals/2
