@baseURL = {{baseURL}}
@baseURL = https://3lretag3s6.execute-api.us-west-2.amazonaws.com/development

###
GET {{baseURL}}/tickets

###

GET {{baseURL}}/animals

###

GET {{baseURL}}/animals/2

###

GET {{baseURL}}/animals?q=E

###

POST {{baseURL}}/animals
Content-Type: application/json

{
  "name": "Toucans",
  "count": "19"
}

###

PATCH {{baseURL}}/animals/2
Content-Type: application/json

{
  "count": 245
}

###

DELETE {{baseURL}}/animals/2
